version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 52774:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
#      - ./:/irisdev/app
